### PR TITLE
Adding z_chain_bottom_anchor.f3d to Gantry folder

### PR DESCRIPTION
**Pull request by emutt11**

### CODE REVIEW

**Comment by matthewlloyd** [comment]
Looks good!

So we don't collide, I'm currently working on side_skirt_*_*_x2.

**Comment by emutt11** [comment]
Thanks for the heads up. I was looking at the skirt earlier trying to think of a clever way of making it parametric for 250, 300, 350 versions. The problem I have is F360 doesn't have a "fill pattern" feature which would make that easier. I'm curious what you come up with.  I will work from the bottom of the 2.4 list and model the z drive stuff next.

**Comment by matthewlloyd** [comment]
Sounds good!

It's messy, but my solution was to create a larger hexagonal mesh pattern than needed (supporting up to 500mm), use an extrude to cut the mesh holes (ignoring the warning that some tool bodies couldn't be created) then re-extrude the outer wall. Then I used a couple of rule fillets for the inner edges. It's almost working! Definitely the most complex I've done so far, apart from the Afterburner blower housing - I attempted it but failed, and I think may require surface patching to get the front profile correct.

**Comment by emutt11** [comment]
Nice, I want to say subconsciously that was my follow up approach just too early on a Saturday to brute force anything. Good luck!

**Pull request merged**
