### PR TITLE
Add Z-Joints to Gantry with model

### PR DESCRIPTION
**Pull request by emutt11**
created z_joint_upper_x4.f3d

Not sure what button I clicked, but for some reason I also have a commit for nozzle_probe.f3d included in this pull request. Not sure how to undo that.

### CODE REVIEW

**Comment by matthewlloyd** [comment]
I am watching and learning - great stuff! Merged. The other commit was automatically removed by GitHub. If you did a git fetch and rebase on the main branch (upstream/main), the commit would have disappeared by itself. Alternatively you could merge the main branch back into your local branch emutt_adding_models.

Don't forget to follow the golden rule of F360: before doing anything, create a component and make sure it's activated! It didn't make any difference for this model, but in some situations it can make certain operations not work correctly if your work isn't inside a component, and if you don't create a component at the start, it's impossible to go back and move all the sketches and operations into a new one.

**Comment by emutt11** [comment]
Thanks for the feedback. 

I could use your help understanding this "golden rule" a bit better. Here is an idea of my current work flow.

I have a top level model locally stored in which each model I have created so far is modeled as a new component. Here is a screen shot of its model tree:

image

Each of the submitted models are "exported" from this model. When I do this the model tree of the new  exported model looks like this:

image

Or is this rule wanting to create a component using the body in the newly exported model:

image

Note that the filename (top item in tree) and the component name (last item in tree) are the same and create a kind of nested model. Seems a bit weird but I am coming around to the component/body assignment. Please confirm if this is what is intended by the  rule.

For now I am still trying to understand the nuances of F360, just glad they finally added middle mouse button rotate (that has bothered me for many years, lol). 

I am really enjoying this side project as I wait for my Fysetc kit to arrive and print the parts.

**Comment by matthewlloyd** [comment]
I'm really enjoying having your help - this would be a long project indeed if it was just me! I'm also a relative newcomer to F360 so still getting my head around it all. I don't fully understand why the rule is important yet, but at least a couple of times have made files without following the rule and ended up having to start over for one reason or another.

You can find some background here: https://forums.autodesk.com/t5/fusion-360-design-validate/fusion-360-r-u-l-e-1-and-2/td-p/6581749.

Personally I encountered it when working with extruded joins, where bodies get combined automatically by Fusion 360 but only if they are in the same component. That means if your bodies aren't inside a component and are sitting at the top level, you have less control over what happens and bodies can get joined that you don't want to be. Once a sketch or body is created at the top level, you can't push it down into a component later.

If the part ends up needing two "components" that mesh or are jointed together, you want them to be at the same level in the tree, so if one of the bodies is at the "top level" then the other cannot be at that same level, but you can't move the body from the "top level" down into a component once you have created it. So it makes life much easier later on to have already put it inside a component.

That's my understanding so far anyway, and every instructional video I watch or article I read seems to follow the same rule, so mostly I'm following the experience of the community here.

Of course, with your current workflow, it doesn't matter to you as you edit because you already have a top-level component for each object for maximum flexibility. However - once the files are exported, the bodies sit at the top level of the F3D file with no nested component inside, which means anyone making subsequent edits to the file is going to run into the same set of issues with not following the golden rule.

So if possible, your second approach (as per your last screenshot) with the doubly nested component is going to be the one that makes files which are the most versatile and editable in the future. From a workflow perspective, you can just create two components, one nested in the other, with the same name, under your top level file.

Hope that helps!

**Comment by emutt11** [comment]
Cool, thanks!

I will have to think more about the "extruded joins" moving forward see if I come across a good example.

**Pull request merged**
