### PR TITLE
Add Z_Idlers folder and models

### PR DESCRIPTION
**Pull request by emutt11**
I am new to github. I really don't know if I am submitting this correctly. However, I do have 10+ years CREO/PROE experience and would like to help create the parametric model.

Included is the z_tensioner_bracket_a_x2 with history, and a mirror export of z_tensioner_bracket_b_x2

### CODE REVIEW

**Comment by matthewlloyd** [comment]
Welcome to the project and thanks for helping! I checked these in Fusion, and your reconstructions look extremely exact and precise, down to the chamfer and fillet order on the front face of the tensioner bracket - nice work. The GitHub commits look great and you are submitting this correctly.

You can save yourself some time for future PRs: for models that are mirror images of each other, I've been reconstructing only the "a" or "left" versions. Similarly, for models that differ only in a key parameter like 9mm vs 6mm versions, I've been building only the lowest mm version and using a user parameter. However it's also fine to have both. :)

[a]_z_tensioner_x4_6mm & 9mm look great. I was going to suggest to add a user parameter for the belt width (`z_belt_width`) and set the extrude distance to `z_belt_width + 5.8 mm`, but I notice the 6mm version has an 11.8mm extrude (=6+5.8) while the 9mm has a 15.8mm extrude (=9+6.8). So it will need to be two parameters, `z_belt_width`, and something like `z_idler_travel` with a note to use 5.8 for 6mm and 6.8 for 9mm, as F360 doesn't have conditional expressions. If you get a chance to do this that would be great, otherwise I'll just add it in a later commit.

z_tensioner_bracket_a_x2 (and the b version) also look great. However... I can't see the design history in either file. With luck this is just an import/export issue. I've made the error of not turning on design history at the start a few times, and unfortunately there's no way to get it back retrospectively... you have to reconstruct the part again from scratch :/.

image

**Comment by emutt11** [comment]
Thanks for the feedback, still getting used to the nuances of fusion360. I will work to add the parameters to the [a]_z_tensioner_6mm, and correct the lack of history for the other files (I think my local files still have the history).

How do I update this pull request with new files? Or, do I need to create a new one?

**Comment by matthewlloyd** [comment]
> hanks for the feedback, still getting used to the nuances of fusion360. I will work to add the parameters to the [a]_z_tensioner_6mm, and correct the lack of history for the other files (I think my local files still have the history).

Great!

> How do I update this pull request with new files? Or, do I need to create a new one?

It depends how you created it, but ultimately, any changes you push to your branch emutt11-patch-1 will immediately be reflected in this pull request. So you can either make commits to amend / remove / add files, or you can rebase your commits (i.e. make new ones to replace the existing ones) and force push to your branch. It may be easier to create a new one, if so, that's fine too!

**Comment by matthewlloyd** [comment]
Fantastic, thanks for the fast updates! Merged.

**Pull request merged**
